name: dart_async
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.1 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  very_good_analysis: ^2.3.0
dependencies:
  rxdart: ^0.27.2
